name: library service CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version:
          - "3.11.5"
    
    name: tests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: make venv
        run: python -m venv venv

      - name: start venv
        run: venv\Scripts\activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pytest
        run: python -m pip install pytest 

      - name: Get database
        run: import database

      - name: Start database
        run: init_database()

      - name: Run tests
        run: pytest
